### ISSUE TITLE
wiley-njd quarto extension ready for use?

### ISSUE THREAD

**Issue by maxdrohde** [ramiromagno/wiley-njd#5]
Thank you for making this Quarto extension! I started making a similar extension myself, until I found that you had already done it. Is this ready for use, or still in development? If so, are you planning to publish it to the official quarto journals repository?

**Comment by ramiromagno** [comment]
Hello Maximilian,

I appreciate your message!

The project is currently in the development phase, and this marks my initial venture into creating a Quarto extension. However, please don't hesitate to fork the project and customize it to suit your requirements, or even consider contributing if you're inclined to do so. Your assistance would be greatly appreciated, and I'm open to any collaboration.

Best regards,

**Comment by ramiromagno** [comment]
Hi @maxdrohde:

I hope my answer was satisfactory. I close this issue for now but feel free to ask further questions.
