### ISSUE TITLE
Rmarkdown version

### ISSUE THREAD

**Issue by schneiderpy** [ramiromagno/wiley-njd#6]
Hi Ramiro
Since I am not so familar yet with Quarto, is there a .rmd version?

**Comment by ramiromagno** [comment]
Hi Andreas,

I don't think so; not that I am aware of, at least. A quick look at the [rticles package](https://github.com/rstudio/rticles) does not show anything for Wiley. Sorry!

**Comment by schneiderpy** [comment]
Thank you ...
