### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by schneiderpy** [ramiromagno/wiley-njd#7]
Hi Ramiro
I have managed somehow to install the extension (living in the same folder with a basic .qmd file - created from New file -> quarto file). After about 8 min. of installing and updating (LaTex?) packages I received a message:
updating tlmgr

updating existing packages

compilation failed- error
Undefined control sequence.
l.3 \setcitestyle
                 {} 
What could be the source of this error?

**Comment by ramiromagno** [comment]
It is difficult for me to understand what went wrong without an example. Can you provide your qmd for me to replicate the issue?

**Comment by schneiderpy** [comment]
Thank you Ramiro .. here part of a screeshot to give you more context. First part, the entire .qmd file. Below, rendering results

![Screenshot 2023-10-14_qmd](https://github.com/ramiromagno/wiley-njd/assets/77991319/1ebc8b01-3f1f-46c3-91c7-20c95c2c3b31)
[](url)

**Comment by ramiromagno** [comment]
Hi @schneiderpy : 

I only see the snapshot. Could you send me the qmd? Thanks!

**Comment by schneiderpy** [comment]
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
14/10/23,
15:44:04

**Comment by schneiderpy** [comment]
@ramiromagno/wiley-njd
***@***.***>  could
you be so kind and check if the rendering produces a "nul" file?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
14/10/23,
15:46:17

**Comment by ramiromagno** [comment]
Hi @schneiderpy: 

Your replies directly from email seem to be scrambled. Could you reply from within GitHub instead? And attach the qmd?

**Comment by schneiderpy** [comment]
qmd is not supported

**Comment by ramiromagno** [comment]
Okay, just zip it then.

**Comment by schneiderpy** [comment]
or you should pass me your email .. to attach the .qmd file

**Comment by schneiderpy** [comment]
[lince.zip](https://github.com/ramiromagno/wiley-njd/files/12907675/lince.zip)

**Comment by schneiderpy** [comment]
Thank you
