### ISSUE TITLE
Compilation failes - Latex

### ISSUE THREAD

**Issue by schneiderpy** [ramiromagno/wiley-njd#8]
I am sorry @ramiromagno, but it seems there is another bug
I used the same qmd file. After the first fix #7, rendering the file stopped  again.

compilation failed- error
LaTeX Error: Environment Shaded undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.83 \begin{Shaded}

**Comment by ramiromagno** [comment]
Indeed :)
The Wiley template was not designed to account for R code chunks. But I am looking for quick fix right now. I will keep you posted.

**Comment by schneiderpy** [comment]
@ramiromagno ... I just found a solution .. worked (or at least rendered) :)
https://stackoverflow.com/questions/41052687/rstudio-pdf-knit-fails-with-environment-shaded-undefined-error
@ramiromagno, thank you for your time!

**Comment by schneiderpy** [comment]
... the numbering of the headers is also different

**Comment by ramiromagno** [comment]
You should start the level 1 headings with `#`, not `##`.

**Comment by schneiderpy** [comment]
That is true .. :)

> @ramiromagno ... I just found a solution .. worked (or at least rendered) :) https://stackoverflow.com/questions/41052687/rstudio-pdf-knit-fails-with-environment-shaded-undefined-error @ramiromagno, thank you for your time!

Due to this fix another error poped up since you have implemented somewhere else, but I manged to fix it (this is great for someone with almost no LaTex knowlegde :) )
Again, thank you @ramiromagno. You did a great work on a Saturday evening 💯

**Comment by schneiderpy** [comment]
citation doesn't work either .. :(

**Comment by ramiromagno** [comment]
Please provide an example qmd and the bibliography file and I am glad to try to reproduce it here. And please open a new dedicated issue.

**Comment by schneiderpy** [comment]
[lince.zip](https://github.com/ramiromagno/wiley-njd/files/12908153/lince.zip)
