### ISSUE TITLE
citation does not work

### ISSUE THREAD

**Issue by schneiderpy** [ramiromagno/wiley-njd#9]
[lince.zip](https://github.com/ramiromagno/wiley-njd/files/12908157/lince.zip)

**Comment by ramiromagno** [comment]
You need to place this code in your qmd file where you want the bibliography to be generated:

```
\bibliography{ {{< meta bibliography >}} }
```

**Comment by schneiderpy** [comment]
I thought that I specified this in the YAML header ...?

**Comment by ramiromagno** [comment]
Hi Andreas,

No, in the yaml header you specify which bib file to provide the bibliography. The command above-mentioned indicates where the bibliography is actually generated, and if you don't add that command the citations in the text won't be generated either. So that is why.

**Comment by schneiderpy** [comment]
There reference now appears, but there is still no citiation in the text ...

**Comment by ramiromagno** [comment]
I can have a look at it again, if you send me the updated qmd and bib file. If you prefer, you can send me an email. My email is in the DESCRIPTION file in this repo.

**Comment by schneiderpy** [comment]
I cannot find a DESCRIPTION file

**Comment by ramiromagno** [comment]
I apologize! I was in the mindset of R package development... rmagno at pattern.institute.

**Comment by ramiromagno** [comment]
My reply followed by email.
